export { default } from '../../clubnests_2.jsx'
import { useEffect, useRef } from "react";
import ClubNests from "../../clubnests_2.jsx";

// Replace YOUTUBE_ID_1 and YOUTUBE_ID_2 with real ClubNests video IDs
const VIDEOS = [
  { id: "YOUTUBE_ID_1", tag: "SS26",      title: "NEST DROP LOOKBOOK" },
    { id: "YOUTUBE_ID_2", tag: "OT.DANIEL", title: "BEHIND THE STITCH"  },
    ];

    function VideoSection() {
      return (
          <section style={{ background: "#0e1f0e", padding: "48px 20px 32px" }}>
                <style>{`
                        .cn-vl{color:#c9a84c;font-family:'Space Grotesk',sans-serif;font-size:11px;letter-spacing:3px;text-transform:uppercase;margin-bottom:8px}
                                .cn-vh{font-family:'Bebas Neue',sans-serif;font-size:42px;color:#fff;line-height:1;margin-bottom:24px}
                                        .cn-vh span{color:#c9a84c}
                                                .cn-vg{display:grid;grid-template-columns:1fr 1fr;gap:12px}
                                                        .cn-vc{position:relative;border-radius:14px;overflow:hidden;background:#162816;aspect-ratio:9/16}
                                                                .cn-vc iframe{width:100%;height:100%;border:none}
                                                                        .cn-vo{position:absolute;bottom:0;left:0;right:0;background:linear-gradient(to top,rgba(14,31,14,.95) 0%,transparent 60%);padding:16px 12px 12px}
                                                                                .cn-vt{display:inline-block;background:#c9a84c;color:#0e1f0e;font-family:'Bebas Neue',sans-serif;font-size:10px;letter-spacing:1.5px;padding:2px 7px;border-radius:4px;margin-bottom:4px}
                                                                                        .cn-vn{font-family:'Bebas Neue',sans-serif;font-size:15px;color:#fff;letter-spacing:.5px}
                                                                                                .cn-vb{display:block;width:100%;margin-top:20px;padding:14px;background:transparent;border:1.5px solid rgba(201,168,76,.27);border-radius:12px;color:#c9a84c;font-family:'Bebas Neue',sans-serif;font-size:16px;letter-spacing:2px;cursor:pointer;text-align:center}
                                                                                                      `}</style>
                                                                                                            <p className="cn-vl">NEST CULTURE</p>
                                                                                                                  <h2 className="cn-vh">THE <span>VIBE</span><br />IN MOTION</h2>
                                                                                                                        <div className="cn-vg">
                                                                                                                                {VIDEOS.map((v, i) => (
                                                                                                                                          <div key={i} className="cn-vc">
                                                                                                                                                      <iframe src={`https://www.youtube.com/embed/${v.id}?controls=1&rel=0`} allowFullScreen title={v.title} />
                                                                                                                                                                  <div className="cn-vo">
                                                                                                                                                                                <div className="cn-vt">{v.tag}</div>
                                                                                                                                                                                              <div className="cn-vn">{v.title}</div>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                        <button className="cn-vb">SEE ALL VIDEOS</button>
                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                              export default function App() {
                                                                                                                                                                                                                                                const ref = useRef(null);

                                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                                      const inject = () => {
                                                                                                                                                                                                                                                            const el = ref.current;
                                                                                                                                                                                                                                                                  if (!el) return;
                                                                                                                                                                                                                                                                        const target = Array.from(document.querySelectorAll("*")).find(
                                                                                                                                                                                                                                                                                (n) =>
                                                                                                                                                                                                                                                                                          n.children.length > 0 &&
                                                                                                                                                                                                                                                                                                    n.textContent.includes("Nest Picks") &&
                                                                                                                                                                                                                                                                                                              n.textContent.includes("SS26") &&
                                                                                                                                                                                                                                                                                                                        n !== document.body &&
                                                                                                                                                                                                                                                                                                                                  n !== document.documentElement
                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                              if (target && target.parentElement) {
                                                                                                                                                                                                                                                                                                                                                      target.parentElement.insertBefore(el, target);
                                                                                                                                                                                                                                                                                                                                                              el.style.display = "block";
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                            const t = setTimeout(inject, 700);
                                                                                                                                                                                                                                                                                                                                                                                return () => clearTimeout(t);
                                                                                                                                                                                                                                                                                                                                                                                  }, []);

                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                                                                              <ClubNests />
                                                                                                                                                                                                                                                                                                                                                                                                    <div ref={ref} style={{ display: "none" }}>
                                                                                                                                                                                                                                                                                                                                                                                                            <VideoSection />
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                        }